title: Welcome to my Blog
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linaleona.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Lina Gildenstern
author-image:   1234.jpg
author-job:     Student
author-email:   lina.gildenstern@web.de  # Add your email for contant form.
author-twitter: linalivelyx # Add your twitter account
about-author:   Student| Dancer| Writer| Artist.

# Social settings
social-twitter:   linalivelyx
social-facebook:
social-github:    
social-pinterest: 
social-instagram: lina.leona
social-youtube:
social-vk:   
social-linkedin:


# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1


# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
